{
  "language": "node_js",
  "node_js": "node",
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "script": [
    "npm build",
  ],

  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}

